### ISSUE TITLE
 error 'Dapphp\TorUtils\ControlClient' not found when using TorUtils in Laravel

### ISSUE THREAD

**Issue by cvlug** [dapphp/TorUtils#1] opened 2016-01-16 12:10 UTC
With composer i have imported TorUtils
("require": {
        "laravel/framework": "5.1.*",  
        "dapphp/TorUtils":"dev-master")

When i use TorUtils like:
use Dapphp\TorUtils\ControlClient;
use Dapphp\TorUtils\ProtocolError;
$tc = new ControlClient();

try {
    $tc->connect(); // connect to 127.0.0.1:9051
    $tc->authenticate(); // uses cookie authentication, can also use $tc->authenticate('password_here');
} catch (\Exception $ex) {
    echo "Failed to create Tor control connection: " . $ex->getMessage() . "\n";
    exit;
}

try {
    echo "Sending NEWNYM signal to controller...";
    $tc->signal(ControlClient::SIGNAL_NEWNYM);
    echo "OK";
} catch (ProtocolError $pe) {
    echo $pe->getMessage();
}

$tc->quit(); // close control connection

i get the error 'Dapphp\TorUtils\ControlClient' not found.
It seems the files are in the right place: is see: laravel\vendor\dapphp\torutils\src\ControlClient.php

i olso tried use dapphp\torUtils\controlClient; and several other things without succes.
How to get this class word in Laravel?

**Comment by dapphp** [comment] 2016-06-22 16:39
Hi, I totally missed the notification of this issue so I'm probably far too late.  Did you ever get it working?

I'll play around and see if I can reproduce the issue and come up with a solution.

**Comment by cvlug** [comment] 2016-06-22 19:14
Hi,

I don’t remember.

I don’t think so,

Regards,

Charles

Van: Drew Phillips [mailto:notifications@github.com] 
Verzonden: woensdag 22 juni 2016 18:40
Aan: dapphp/TorUtils
CC: cvlug; Author
Onderwerp: Re: [dapphp/TorUtils] error 'Dapphp\TorUtils\ControlClient' not found when using TorUtils in Laravel (#1)

Hi, I totally missed the notification of this issue so I'm probably far too late. Did you ever get it working?

I'll play around and see if I can reproduce the issue and come up with a solution.

**Comment by dapphp** [comment] 2016-06-23 07:17
I had an older Laraval 5.1 app running so I tested with it and it worked fine.

It might be the newer version of TorUtils / composer.json but since I added the composer file nothing with the structure has changed.  That error would indicate the autoloader didn't properly map the files (or the autoloader wasn't included, but this seems unlikely).

If you decide to give it another go, let me know if I can help.  Closing this for now but feel free to re-open or contact me directly.

**Closed as completed by dapphp** 2016-06-23 07:17 UTC

**Comment by cvlug** [comment] 2016-06-23 08:51
Thanks!

Van: Drew Phillips [mailto:notifications@github.com] 
Verzonden: donderdag 23 juni 2016 09:18
Aan: dapphp/TorUtils
CC: cvlug; Author
Onderwerp: Re: [dapphp/TorUtils] error 'Dapphp\TorUtils\ControlClient' not found when using TorUtils in Laravel (#1)

I had an older Laraval 5.1 app running so I tested with it and it worked fine.

It might be the newer version of TorUtils / composer.json but since I added the composer file nothing with the structure has changed. That error would indicate the autoloader didn't properly map the files (or the autoloader wasn't included, but this seems unlikely).

If you decide to give it another go, let me know if I can help. Closing this for now but feel free to re-open or contact me directly.
